# Generated by Django 5.2.1 on 2025-08-19 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.profile', verbose_name='Начальник'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_internal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Внутренний номер'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Начальник отдела'), ('director', 'Генеральный директор')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
